name: Tests

on:
  push:
    paths-ignore:
      - ".md"
    branches:
      - main
  pull_request:
    paths-ignore:
      - "*.md"
    branches:
      - main

jobs:
  main:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true
      - run: pnpm build
      - run: pnpm test
